"""
api_server.py — External REST API for the Essay Accuracy Checker (Stage 2)

Exposes the essay-accuracy pipeline over HTTP so other modules in this
project (e.g. Module 3) can submit a Sinhala essay — as JSON text or as an
uploaded .txt file — and get back the same score, claim-by-claim verdicts,
and teacher-style corrective feedback the Streamlit UI shows — without
importing this project's Python code.

Run with:
    venv/Scripts/uvicorn api_server:app --host 0.0.0.0 --port 8010

Interactive API docs (auto-generated by FastAPI) are then available at
http://localhost:8010/docs

Auth: every request must include a valid X-API-Key header. Keys and their
associated caller names are configured via ESSAY_API_KEYS in .env — see
.env.example. This identifies *which module* called (stored as `caller`
on every saved run); callers may additionally pass `submitted_by` in the
request body for their own tracing (e.g. a student/essay ID).
"""

from __future__ import annotations

import json
import os
import time
from typing import Optional

from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, Header, HTTPException, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field, ValidationError

load_dotenv()

import essay_accuracy_checker as eac
import mongo_store

ANTHROPIC_API_KEY: str = os.environ.get("ANTHROPIC_API_KEY", "")


# API key configuration — "key1:CallerName,key2:OtherCaller" from .env

def _load_api_keys() -> dict[str, str]:
    raw = os.environ.get("ESSAY_API_KEYS", "")
    keys: dict[str, str] = {}
    for pair in raw.split(","):
        pair = pair.strip()
        if not pair or ":" not in pair:
            continue
        key, _, name = pair.partition(":")
        key = key.strip()
        name = name.strip() or "unknown"
        if key:
            keys[key] = name
    return keys


_API_KEYS: dict[str, str] = _load_api_keys()


def _authenticate(x_api_key: Optional[str]) -> str:
    """Validate the X-API-Key header and return the caller's display name."""
    if not _API_KEYS:
        raise HTTPException(
            status_code=503,
            detail="No API keys configured on the server — set ESSAY_API_KEYS in .env.",
        )
    if not x_api_key or x_api_key not in _API_KEYS:
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header.")
    return _API_KEYS[x_api_key]


# App

app = FastAPI(
    title="Sinhala Historical Essay Accuracy API",
    description=(
        "Submit a raw Sinhala historical essay and receive a Knowledge-Graph-"
        "grounded accuracy score, claim-by-claim verdicts, and teacher-style "
        "corrective feedback for any factual errors."
    ),
    version="1.0.0",
)

# Internal, trusted multi-module project — permissive CORS. Tighten
# allow_origins to specific module URLs if this is ever exposed externally.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# Request / response schemas

class EssayCheckRequest(BaseModel):
    essay_text: str = Field(..., min_length=1, description="Raw Sinhala historical essay text to check.")
    submitted_by: Optional[str] = Field(
        None,
        description="Optional caller-supplied identifier (e.g. student ID, essay ID) for the caller's own traceability.",
    )


class ClaimResponse(BaseModel):
    claim_sinhala: str
    claim_type: str
    verdict: str
    unverifiable_reason: Optional[str]
    matched_kg_fact: str
    explanation: str
    teacher_feedback: Optional[str]
    batch_number: int


class EssayCheckResponse(BaseModel):
    request_id: str
    caller: str
    essay_subject: str
    all_kings_found: list[str]
    accuracy_score: Optional[float]
    coverage_ratio: float
    confidence_level: str
    coverage_warning: bool
    total_claims: int
    total_factual_claims: int
    editorial_claims: int
    correct_claims: int
    incorrect_claims: int
    unverifiable_claims: int
    kg_gap_claims: int
    not_factual_claims: int
    kg_facts_used: int
    batch_count: int
    essay_sentence_count: int
    claims: list[ClaimResponse]
    processing_seconds: float


def _claim_to_response(c) -> ClaimResponse:
    return ClaimResponse(
        claim_sinhala=c.claim_sinhala,
        claim_type=c.claim_type,
        verdict=c.verdict,
        unverifiable_reason=c.unverifiable_reason,
        matched_kg_fact=c.matched_kg_fact,
        explanation=c.explanation,
        teacher_feedback=c.teacher_feedback,
        batch_number=c.batch_number,
    )


# Endpoints

@app.get("/api/v1/health")
def health() -> dict:
    """Unauthenticated liveness/config check — safe to poll without a key."""
    return {
        "status": "ok",
        "anthropic_key_configured": bool(ANTHROPIC_API_KEY),
        "api_keys_configured": len(_API_KEYS),
    }


async def _parse_essay_check_body(request: Request) -> EssayCheckRequest:
    """Parse the request body leniently instead of via FastAPI's default
    strict JSON decoding.

    Callers overwhelmingly paste multi-paragraph essay text straight into
    a JSON string field (Postman's raw editor, curl -d, etc.) without
    escaping the line breaks as \\n — technically invalid per RFC 8259,
    but the single most common real-world shape of this endpoint's input,
    and not something we can dictate away from every caller. Python's
    json module supports this directly via strict=False (tolerates literal
    control characters — raw newlines, tabs — inside string values instead
    of raising "Invalid control character at ..."), so we read the raw
    body ourselves and parse it that way rather than needing every caller
    to pre-escape their text.
    """
    raw_bytes = await request.body()
    try:
        raw_text = raw_bytes.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise HTTPException(status_code=400, detail=f"Request body is not valid UTF-8: {exc}") from exc

    try:
        parsed = json.loads(raw_text, strict=False)
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=422, detail=f"Body is not valid JSON: {exc}") from exc

    try:
        return EssayCheckRequest.model_validate(parsed)
    except ValidationError as exc:
        raise HTTPException(status_code=422, detail=exc.errors()) from exc


def _run_and_save(essay_text: str, caller: str, submitted_by: Optional[str]) -> EssayCheckResponse:
    """Shared core: run the check, save it, build the response. Used by
    both the JSON endpoint and the file-upload endpoint so the two never
    drift apart in behavior."""
    if not ANTHROPIC_API_KEY:
        raise HTTPException(status_code=500, detail="ANTHROPIC_API_KEY is not configured on the server.")

    essay_text = essay_text.strip()
    if not essay_text:
        raise HTTPException(status_code=400, detail="essay_text must not be empty.")

    started = time.monotonic()
    try:
        result = eac.check_essay_accuracy(essay_text, ANTHROPIC_API_KEY)
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Essay check failed: {exc}") from exc
    elapsed = time.monotonic() - started

    run_id = mongo_store.save_essay_check_run(
        essay_text, result,
        source="api", caller=caller, submitted_by=submitted_by,
    )

    return EssayCheckResponse(
        request_id=run_id or "unsaved",
        caller=caller,
        essay_subject=result.essay_subject,
        all_kings_found=result.all_kings_found,
        accuracy_score=result.accuracy_score,
        coverage_ratio=result.coverage_ratio,
        confidence_level=result.confidence_level,
        coverage_warning=result.coverage_warning,
        total_claims=result.total_claims,
        total_factual_claims=result.total_factual_claims,
        editorial_claims=result.editorial_claims,
        correct_claims=result.correct_claims,
        incorrect_claims=result.incorrect_claims,
        unverifiable_claims=result.unverifiable_claims,
        kg_gap_claims=result.kg_gap_claims,
        not_factual_claims=result.not_factual_claims,
        kg_facts_used=result.kg_facts_used,
        batch_count=result.batch_count,
        essay_sentence_count=result.essay_sentence_count,
        claims=[_claim_to_response(c) for c in result.all_claim_results],
        processing_seconds=round(elapsed, 2),
    )


@app.post(
    "/api/v1/essay/check",
    response_model=EssayCheckResponse,
    # Body is parsed manually (see _parse_essay_check_body) instead of via
    # a FastAPI-native `body: EssayCheckRequest` parameter, so Swagger/
    # /docs would otherwise show no schema for it — openapi_extra restores
    # the example/schema in the docs even though parsing bypasses it.
    openapi_extra={
        "requestBody": {
            "required": True,
            "content": {"application/json": {"schema": EssayCheckRequest.model_json_schema()}},
        }
    },
)
async def check_essay(
    request: Request,
    x_api_key: Optional[str] = Header(None, alias="X-API-Key"),
) -> EssayCheckResponse:
    """Submit essay_text as JSON. See /api/v1/essay/check-file to upload
    a .txt file instead."""
    caller = _authenticate(x_api_key)
    body = await _parse_essay_check_body(request)
    return _run_and_save(body.essay_text, caller, body.submitted_by)


@app.post("/api/v1/essay/check-file", response_model=EssayCheckResponse)
async def check_essay_file(
    file: UploadFile = File(..., description="A .txt file containing the Sinhala essay, UTF-8 encoded."),
    submitted_by: Optional[str] = Form(None),
    x_api_key: Optional[str] = Header(None, alias="X-API-Key"),
) -> EssayCheckResponse:
    """Submit the essay as an uploaded .txt file (multipart/form-data)
    instead of embedding it in a JSON string — no escaping to worry about
    at all, since there's no JSON string involved. Same scoring pipeline
    and response shape as /api/v1/essay/check."""
    caller = _authenticate(x_api_key)

    raw_bytes = await file.read()
    if not raw_bytes:
        raise HTTPException(status_code=400, detail="Uploaded file is empty.")
    try:
        essay_text = raw_bytes.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise HTTPException(status_code=400, detail=f"File is not valid UTF-8 text: {exc}") from exc

    return _run_and_save(essay_text, caller, submitted_by)


@app.get("/api/v1/essay/{run_id}")
def get_essay_result(
    run_id: str,
    x_api_key: Optional[str] = Header(None, alias="X-API-Key"),
) -> dict:
    """Re-fetch a previously computed result by its request_id — lets a
    caller poll for or re-download a result without re-checking the essay."""
    _authenticate(x_api_key)
    doc = mongo_store.get_essay_run_by_id(run_id)
    if doc is None:
        raise HTTPException(status_code=404, detail="No essay check found with that ID.")
    return doc
